name = "sharescreen"
compatibility_date = "2025-08-31"

pages_build_output_dir = "public"

[vars]
STUN_URLS = "stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302,stun:stun2.l.google.com:19302,stun:stun3.l.google.com:19302,stun:stun4.l.google.com:19302"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"
script_name = "sharescreen-worker"
